name: build

on:
  pull_request:
  workflow_run:
    # Use a workflow as a trigger of scheduled builds. Forked repositories can disable scheduled builds by disabling
    # "scheduled" workflow, while maintaining ability to perform local CI builds.
    workflows:
      - scheduled
    branches:
      - master
    types:
      - requested

jobs:
  Windows:
    runs-on: windows-2022
    if: github.event.pull_request.draft == false
    env:                  
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        shell: cmd
        run: |
          cd src
          git clone --depth=1 https://github.com/stevewgr/ko-vendor.git vendor

      - name: Build KnightOnLine (x86)
        shell: cmd
        run: |
          cd src\game
          "%MSBUILD_PATH%\MSBuild.exe" WarFare.sln /p:Configuration=Release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: KnightOnLine-x86-release
          path: ./src/game/KnightOnLine.exe
